//
//  ReactViewController.swift
//  AigensIOSPlayground
//
//  Created by Peter Liu on 12/10/2016.
//  Copyright © 2016 Aigens. All rights reserved.
//

import Foundation
import React

class ReactViewController: UIViewController {
    
   
    var method : String!
    var bridge : RCTBridge!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        
        switch method {
        case "ReactList":
            setupList()
        default:
            debugPrint("Unknown Method", method)
        }
        
        
        
    }
    
    /*
     jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
     
     /**
     * OPTION 2
     * Load from pre-bundled file on disk. The static bundle is automatically
     * generated by the "Bundle React Native code and images" build step when
     * running the project on an actual device or running the project on the
     * simulator in the "Release" build configuration.
     */
     
     //   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
     
     RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
     moduleName:@"Project"
     initialProperties:nil
     launchOptions:launchOptions];
 */
    
    func setupList(){
        
        debugPrint("setupList");
        
        let jsCodeLocation = URL(string: "http://192.168.111.166:8081/index.ios.bundle?platform=ios&dev=true")
        
        self.bridge = RCTBridge(bundleURL: jsCodeLocation, moduleProvider: nil, launchOptions: nil)
        
        /*
        let rootView = RCTRootView(
            bundleURL: jsCodeLocation,
            moduleName: "ReactNativePlayground",
            initialProperties: nil,
            launchOptions: nil
        )*/
        
        let rootView = RCTRootView(bridge: bridge, moduleName: "ReactNativePlayground", initialProperties: nil)
        
        let vc = UIViewController()
        vc.view = rootView
        self.present(vc, animated: true, completion: nil)
        
        
    }
    
    
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    
    
}
